/**:
  ros__parameters:
    default_firmware_params:
      ring:
        effect: 1
      commander:
        enHighLevel: 1
      stabilizer:
        estimator: 2
        controller: 2
      locSrv:
        extPosStdDev: 1e-2
        extQuatStdDev: 0.5e-1
      ctrlMel:
        kp_xy: 0.4
        kd_xy: 0.2
        ki_xy: 0.05
        i_range_xy: 2.0
        kR_xy: 70000
        kw_xy: 20000
        kR_z: 60000
        kw_z: 12000
        ki_m_z: 500
        i_range_m_z: 1500
        kd_omega_rp: 200
        kp_z: 1.25
        kd_z: 0.4
        ki_z: 0.05
        i_range_z: 0.4
        mass: 0.037
        massThrust: 132000